export const SET_PLACES = 'SET_PLACES';

export const TRY_AUTH = 'TRY_AUTH';

export const UI_START_LOADING = 'UI_START_LOADING';
export const UI_STOP_LOADING = 'UI_STOP_LOADING';

export const DELETE_PLACES = 'DELETE_PLACES';
export const DELETE_PLACES_START = 'DELETE_PLACES_START';
export const DELETE_PLACES_SUCCESS = 'DELETE_PLACES_SUCCESS';
export const DELETE_PLACES_FAIL = 'DELETE_PLACES_FAIL';
